// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDClrTt74NyVgLtBtqnxJRnH2yYv1Qacq4',
    appId: '1:817546613027:web:bf253e9a0c24f7612ebc96',
    messagingSenderId: '817546613027',
    projectId: 'patitentflutter',
    authDomain: 'patitentflutter.firebaseapp.com',
    databaseURL: 'https://patitentflutter-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'patitentflutter.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBdsJZTQOeeSrv-dvy5K6IykI8pPtuUm18',
    appId: '1:817546613027:android:7b3cd2a73b0f969c2ebc96',
    messagingSenderId: '817546613027',
    projectId: 'patitentflutter',
    databaseURL: 'https://patitentflutter-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'patitentflutter.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA6fZKTikvQiSmnU3dWoNcNaLsCBJ5Pktg',
    appId: '1:817546613027:ios:14368d93b7bb78192ebc96',
    messagingSenderId: '817546613027',
    projectId: 'patitentflutter',
    databaseURL: 'https://patitentflutter-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'patitentflutter.appspot.com',
    iosClientId: '817546613027-6ht4njob3qkcbqlkkaj0flrqdkftnk6h.apps.googleusercontent.com',
    iosBundleId: 'com.example.patientApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA6fZKTikvQiSmnU3dWoNcNaLsCBJ5Pktg',
    appId: '1:817546613027:ios:14368d93b7bb78192ebc96',
    messagingSenderId: '817546613027',
    projectId: 'patitentflutter',
    databaseURL: 'https://patitentflutter-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'patitentflutter.appspot.com',
    iosClientId: '817546613027-6ht4njob3qkcbqlkkaj0flrqdkftnk6h.apps.googleusercontent.com',
    iosBundleId: 'com.example.patientApp',
  );
}
